apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: python-storageclass
  resources:
    requests: 
      storage: 5Gi
